### ISSUE TITLE
How do I change the address of the health bar and change the display of armor?

### ISSUE THREAD

**Issue by andylee10001** [bbgsm/ADM#1]
How do I change the address of the health bar and change the display of armor?

**Comment by bbgsm** [comment]
I only plotted the percentage of health value plus shield. If you want to make modifications, here is the original plotting code:
` ImDrawList *draw = ImGui::GetForegroundDrawList();
    float ww = (std::max)(w, 100.0F);
    ImVec2 progressBarSize(ww, 10);
    ImVec2 progressBarPosition{x - progressBarSize.x / 2, y - 12};

    // 绘制血条背景
    ImVec2 barEndPos{progressBarPosition.x + progressBarSize.x, progressBarPosition.y + progressBarSize.y};
    draw->AddRectFilled(progressBarPosition, barEndPos, IM_COL32(200, 200, 200, 255)); // 灰色背景

    // 计算血条填充部分
    float progressWidth = progressBarSize.x * (player.health / 100.0f);
    ImVec2 progressEnd{progressBarPosition.x + progressWidth, barEndPos.y};
    draw->AddRectFilled(progressBarPosition, progressEnd, IM_COL32(0, 255, 0, 255)); // 绿色填充

    // 绘制血条边框
    draw->AddRect(progressBarPosition, barEndPos, IM_COL32(0, 0, 0, 255), 0, 15); // 黑色边框`
