### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Kprobem** [bbgsm/ADM#4]
![屏幕截图 2024-10-09 114555](https://github.com/user-attachments/assets/983e853b-9be8-4a87-a768-374e8333606a)
尝试搜索该问题好像是由于重复引用文件引起的,不知道怎么解决

**Comment by Kprobem** [comment]
main中加入#include "CheatEngine/cepluginsdk.h"
后出现kmbox报错
注释掉kmbox相关正常编译

**Comment by bbgsm** [comment]
ce 模块这部分我还没完善，kmbox的我等下看看

**Comment by bbgsm** [comment]
还有就是建议用Clion来编译

**Comment by Kprobem** [comment]
测试了除kmbox外,物资显示有点问题。雷达不可用

**Comment by bbgsm** [comment]
已在dev分支修复这个错误，后面会合并到main分支
