### ISSUE TITLE
出现一个编译错误

### ISSUE THREAD

**Issue by CKJ7921** [bbgsm/ADM#8]
![QQ截图20241016032906](https://github.com/user-attachments/assets/99827b3d-f2b0-477c-8bf6-16c2907cb7c6)

**Comment by CKJ7921** [comment]
文件丝毫没动，用的是CLINE，里面也设置了VS和CMAKE。结果到这一步卡住了

**Comment by bbgsm** [comment]
你这是少文件要用这个命令克隆哦 git clone --recursive https://github.com/bbgsm/ADM.git
